### PR TITLE
Adafruit rp2040 feather MCU board

### PR DESCRIPTION
**Pull request by DTPrince**
Added support for the larger 'feather'-form RP2040 board from [Adafruit](https://www.adafruit.com/product/4884#technical-details). 

Have not printed a test yet but the .glb file was created from their [STL](https://github.com/adafruit/Adafruit_CAD_Parts/blob/main/4884%20Feather%20RP2040/4884%20Feather%20RP2040.stl) and dimensions taken from the [Adafruit PCB schematics](https://learn.adafruit.com/adafruit-feather-rp2040-pico/downloads).

### CODE REVIEW

**Comment by rianadon** [comment]
Awesome! Thanks a lot for putting this together. I've always found the Adafruit STLs and dimensions to be accurate so I don't mind merging this in before running a test print.

It looks like there's two little formatting errors unfortunately. You could [install dprint](https://dprint.dev/install/) and then run `dprint fmt` to autoformat everything or manually fix them yourself from the workflow results.

My only other nit is that you edited `VisualEditor.svelte` so that the default connector choice for the board is a single USB socket. Afaik this board doesn't have bluetooth, so how would you connect the halves?

**Comment by DTPrince** [comment]
Whoops, right you are about the connector. I changed it to default back to USB + TRRS and ran `dmprint fmt` on the files.

**Comment by DTPrince** [comment]
The microcontrollers finally came the mail today so I figured I'd print out a test MCU holder. The dimensions/hole placements are accurate to the real product as expected but the board has an edge connector that prohibits the use of the fasten clamps option in the GUI. Additionally there's a rear I2C connector that gets blocked by the backstop being raised above the side edges/PCB which does not block the board from sliding in but is a little unfortunate.

I know (from the Discord discussions) that there are a lot of cool developments planned but I'm not sure if they would address this without focused effort or if it's simply out of scope.

I'm completely content modifying the CAD locally for my project; I was just hoping to help contribute to your cool project!

image

**Comment by rianadon** [comment]
Sorry about not being very responsive on this! I'm trying to hurry and finish V3 of the interface by the end of June, so I won't be able to merge until then. I am still very interested in adding support for the board though once that's finished.

Since the board has 4 holes on it, so I'm not too worried about the fasten clamps colliding with the connector. They are easy enough to snap off when they get in the way. With 3 tabs + 1 screw through the board, it should stay in plenty well.

I'll add an option for backstop height to the microcontroller definitions so that there's enough room for the stemma connector and of course increase the spacing between the microcontroller and TRRS as I mentioned on Discord. Hopefully that would be everything that's needed 🤞🤞

**Comment by rianadon** [comment]
image

I think this should work? I've already corrected the distance between the microcontroller and TRRS socket, and I've just added an option for the backstop. The backstop here comes up the the top surface of the PCB but not any taller.

**Pull request merged**
